export const student1 =[
    {
        id:1,
        name:"sakib",
        imageSrc:"../assets/avatar.png",
        grade:"A+",
        percentage:"98%",
    },
    {
        id:2,
        name:"Rakib",
        grade:"A-",
        percentage:"95%",
    },
    {
        id:3,
        name:"Nokib",
        grade:"A",
        percentage:"92%",
    },
    {
        id:4,
        name:"Piyas",
        grade:"A+",
        percentage:"96%",
    },
    {
        id:5,
        name:"abjal",
        grade:"A+",
        percentage:"92%",
    },
    {
        id:5,
        name:"Rubel",
        grade:"A+",
        percentage:"91%",
    },
    {
        id:6,
        name:"Raihan",
        grade:"A",
        percentage:"82%",
    },
    {
        id:7,
        name:"Piyas",
        grade:"A+",
        percentage:"87%",
    },
    {
        id:8,
        name:"Piku",
        grade:"B",
        percentage:"45%",
    },
    {
        id:9,
        name:"Sojol",
        grade:"A",
        percentage:"73%",
    },
    {
        id:10,
        name:"soyeb",
        grade:"A-",
        percentage:"68%",
    },
   
]
export const student2 =[
    {
        id:1,
        name:"Rajib",
        imageSrc:"./src/assets/avatar.png",
        grade:"A-",
        percentage:"68%",
    },
    {
        id:2,
        name:"mahbub",
        grade:"A-",
        percentage:"82%",
    },
    {
        id:3,
        name:"Musfiq",
        grade:"A+",
        percentage:"93%",
    },

    {
        id:4,
        name:"Riad",
        grade:"A",
        percentage:"78%",
    },
    {
        id:5,
        name:"Firoj",
        grade:"A+",
        percentage:"83%",
    },
    {
        id:6,
        name:"Nupur",
        grade:"A-",
        percentage:"68%",
    },
    {
        id:7,
        name:"Siam",
        grade:"A+",
        percentage:"89%",
    },
    {
        id:8,
        name:"Sagor",
        grade:"A",
        percentage:"75%",
    },
    {
        id:9,
        name:"Nahid",
        grade:"A",
        percentage:"77%",
    },
    {
        id:10,
        name:"Nagor",
        grade:"A",
        percentage:"79%",
    },


]

